// Code generated by goctl. DO NOT EDIT.
// Source: input.proto

package server

import (
	"context"

	"remarks_monitor/app/input/cmd/rpc/internal/logic"
	"remarks_monitor/app/input/cmd/rpc/internal/svc"
	"remarks_monitor/app/input/cmd/rpc/pb"
)

type InputServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInputServer
}

func NewInputServer(svcCtx *svc.ServiceContext) *InputServer {
	return &InputServer{
		svcCtx: svcCtx,
	}
}

func (s *InputServer) Input(ctx context.Context, in *pb.InputReq) (*pb.InputResp, error) {
	l := logic.NewInputLogic(ctx, s.svcCtx)
	return l.Input(in)
}

func (s *InputServer) Search(ctx context.Context, in *pb.SearchReq) (*pb.SearchResp, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}
