// Code generated by goctl. DO NOT EDIT.
// Source: MapReduce.proto

package server

import (
	"context"
	"remarks_monitor/app/map1/cmd/rpc/map1"

	"remarks_monitor/app/map1/cmd/rpc/internal/logic"
	"remarks_monitor/app/map1/cmd/rpc/internal/svc"
)

type MapServer struct {
	svcCtx *svc.ServiceContext
	map1.UnimplementedMapWorkServer
}

func NewMapServer(svcCtx *svc.ServiceContext) *MapServer {
	return &MapServer{
		svcCtx: svcCtx,
	}
}

func (s *MapServer) MapWork(ctx context.Context, in *map1.GetMapWorkReq) (*map1.GetMapWorkResp, error) {
	l := logic.NewMapWorkLogic(ctx, s.svcCtx)
	return l.MapWork(in)
}
