// Code generated by goctl. DO NOT EDIT.
// Source: map1.proto

package server

import (
	"context"

	"remarks_monitor/app/map1/cmd/rpc/internal/logic"
	"remarks_monitor/app/map1/cmd/rpc/internal/svc"
	"remarks_monitor/app/map1/cmd/rpc/map1"
)

type MapWorkServer struct {
	svcCtx *svc.ServiceContext
	map1.UnimplementedMapWorkServer
}

func NewMapWorkServer(svcCtx *svc.ServiceContext) *MapWorkServer {
	return &MapWorkServer{
		svcCtx: svcCtx,
	}
}

func (s *MapWorkServer) MapWork(ctx context.Context, in *map1.GetMapWorkReq) (*map1.GetMapWorkResp, error) {
	l := logic.NewMapWorkLogic(ctx, s.svcCtx)
	return l.MapWork(in)
}
