// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	_ "net/http/pprof"

	master "remarks_monitor/app/master/cmd/api/internal/handler/master"
	"remarks_monitor/app/master/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/master",
				Handler: master.CoordinatorHandler(serverCtx),
			},
		},
	)
}
