// Code generated by goctl. DO NOT EDIT.
package types

type Info struct {
	Type     string `json:"type"`
	Content  string `json:"content"`
	Nums     int64  `json:"nums"`
	UpdateAt string `json:"updateAt"`
	CreateAt string `json:"createAt"`
}

type MasterReq struct {
	Kind int `json:"kind"`
}

type MasterResp struct {
	Message string `json:"message"`
}

type SearchReq struct {
	Kind   int `json:"kind"`
	Offset int `json:"offset"`
	Num    int `json:"num"`
}

type SearchResp struct {
	Message string `json:"message"`
	Info    []Info `json:"info"`
}
