// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"remarks_monitor/app/input/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/input",
				Handler: inputHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: searchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/searchAll",
				Handler: searchAllHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
