// Code generated by goctl. DO NOT EDIT.
package types

type Info struct {
	Username string `json:"username"`
	Domain   string `json:"domain"`
	Content  string `json:"content"`
	Time     string `json:"time"`
}

type InputRequest struct {
	Info Info `json:"info"`
}

type InputResponse struct {
	Message string `json:"message"`
}

type SearchRequest struct {
}

type SearchResponse struct {
	Info []Info `json:"info"`
}

type SearchAllRequest struct {
	Username string `json:"username"`
}

type SearchAllResponse struct {
	Info []Info `json:"info"`
}
