// Code generated by goctl. DO NOT EDIT.
// Source: MapReduce.proto

package mapwork

import (
	"context"

	"remarks_monitor/app/map/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMapWorkReq  = pb.GetMapWorkReq
	GetMapWorkResp = pb.GetMapWorkResp

	MapWork interface {
		MapWork(ctx context.Context, in *GetMapWorkReq, opts ...grpc.CallOption) (*GetMapWorkResp, error)
	}

	defaultMapWork struct {
		cli zrpc.Client
	}
)

func NewMapWork(cli zrpc.Client) MapWork {
	return &defaultMapWork{
		cli: cli,
	}
}

func (m *defaultMapWork) MapWork(ctx context.Context, in *GetMapWorkReq, opts ...grpc.CallOption) (*GetMapWorkResp, error) {
	client := pb.NewMapWorkClient(m.cli.Conn())
	return client.MapWork(ctx, in, opts...)
}
