// Code generated by goctl. DO NOT EDIT.
// Source: reduce2.proto

package server

import (
	"context"

	"remarks_monitor/app/reduce2/cmd/rpc/internal/logic"
	"remarks_monitor/app/reduce2/cmd/rpc/internal/svc"
	"remarks_monitor/app/reduce2/cmd/rpc/reduce2"
)

type ReduceWork2Server struct {
	svcCtx *svc.ServiceContext
	reduce2.UnimplementedReduceWork2Server
}

func NewReduceWork2Server(svcCtx *svc.ServiceContext) *ReduceWork2Server {
	return &ReduceWork2Server{
		svcCtx: svcCtx,
	}
}

func (s *ReduceWork2Server) ReduceWork2(ctx context.Context, in *reduce2.ReduceWorkReq) (*reduce2.ReduceWorkResp, error) {
	l := logic.NewReduceWork2Logic(ctx, s.svcCtx)
	return l.ReduceWork2(in)
}
