// Code generated by goctl. DO NOT EDIT.
// Source: map3.proto

package server

import (
	"context"

	"remarks_monitor/app/map3/cmd/rpc/internal/logic"
	"remarks_monitor/app/map3/cmd/rpc/internal/svc"
	"remarks_monitor/app/map3/cmd/rpc/map3"
)

type MapWorkServer struct {
	svcCtx *svc.ServiceContext
	map3.UnimplementedMapWorkServer
}

func NewMapWorkServer(svcCtx *svc.ServiceContext) *MapWorkServer {
	return &MapWorkServer{
		svcCtx: svcCtx,
	}
}

func (s *MapWorkServer) MapWork(ctx context.Context, in *map3.GetMapWorkReq) (*map3.GetMapWorkResp, error) {
	l := logic.NewMapWorkLogic(ctx, s.svcCtx)
	return l.MapWork(in)
}
