// Code generated by goctl. DO NOT EDIT.
// Source: map.proto

package server

import (
	"context"

	"remarks_monitor/app/map/cmd/rpc/internal/logic"
	"remarks_monitor/app/map/cmd/rpc/internal/svc"
	"remarks_monitor/app/map/cmd/rpc/pb"
)

type MapTaskServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMapTaskServer
}

func NewMapTaskServer(svcCtx *svc.ServiceContext) *MapTaskServer {
	return &MapTaskServer{
		svcCtx: svcCtx,
	}
}

func (s *MapTaskServer) MapTask(ctx context.Context, in *pb.MapReq) (*pb.MapResp, error) {
	l := logic.NewMapTaskLogic(ctx, s.svcCtx)
	return l.MapTask(in)
}
