// Code generated by goctl. DO NOT EDIT.
// Source: map2.proto

package server

import (
	"context"

	"remarks_monitor/app/map2/cmd/rpc/internal/logic"
	"remarks_monitor/app/map2/cmd/rpc/internal/svc"
	"remarks_monitor/app/map2/cmd/rpc/map2"
)

type MapWorkServer struct {
	svcCtx *svc.ServiceContext
	map2.UnimplementedMapWorkServer
}

func NewMapWorkServer(svcCtx *svc.ServiceContext) *MapWorkServer {
	return &MapWorkServer{
		svcCtx: svcCtx,
	}
}

func (s *MapWorkServer) MapWork(ctx context.Context, in *map2.GetMapWorkReq) (*map2.GetMapWorkResp, error) {
	l := logic.NewMapWorkLogic(ctx, s.svcCtx)
	return l.MapWork(in)
}
