// Code generated by goctl. DO NOT EDIT.
// Source: map.proto

package maptask

import (
	"context"

	"remarks_monitor/app/map/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	MapReq  = pb.MapReq
	MapResp = pb.MapResp
	Task    = pb.Task

	MapTask interface {
		MapTask(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*MapResp, error)
	}

	defaultMapTask struct {
		cli zrpc.Client
	}
)

func NewMapTask(cli zrpc.Client) MapTask {
	return &defaultMapTask{
		cli: cli,
	}
}

func (m *defaultMapTask) MapTask(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*MapResp, error) {
	client := pb.NewMapTaskClient(m.cli.Conn())
	return client.MapTask(ctx, in, opts...)
}
